### PR TITLE
feat: workflow for generating npm libraries backed by workspaces

### PR DESCRIPTION
**Pull request by jsmylnycky**
This assumes using Release Please in "manifest" mode, so the repos will need to include the appropriate manifest file and config pointing to their workspace packages.

During the publish step, if a release was created (by RP) then the publish is tagged with `latest`. If the publish step was hit on a non-release workflow, then the publish is tagged with `next`.

Example of a Release PR: https://github.com/Littera-Education/littera-test-monorepo/pull/2

Follow up PR only bumping one package: https://github.com/Littera-Education/littera-test-monorepo/pull/3

We are only publishing on actual releases, not snapshots, as this is a bit more complex than I want to spend time on right now and there's not a lot of value.

Example of the versions in Nexus:

image

At this time, all versions of all packages will get bumped together until we can spend time on some logic to only publish packages that got updated. Today they would get an error from Nexus due to not being allowed to update an existing.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
image

**Comment by jsmylnycky** [comment]
Repositories need to include a `.release-please-manifest.json` file with the packages listed like:

```
{
  "packages/atoms": "1.9.0",
  "packages/molecules": "1.9.0"
}
```

And a `release-please-config.json` resembling:
```
{
  "packages": {
    "packages/atoms": {
      "component": "atoms"
    },
    "packages/molecules": {
      "component": "molecules"
    }
  },
  "plugins": [{
    "type": "linked-versions",
    "components": [
      "atoms",
      "molecules"
    ]
  }]
}
```

**Comment by jsmylnycky** [comment]
Example run with workspaces enabled (by default):

image

**Comment by jsmylnycky** [comment]
Example run with workspaces disabled:

image

**Review by chrislittera — APPROVED** [review]

**Pull request merged**
